# Disable automatic framework detection by uncommenting/setting to false
# Warbler.framework_detection = false
 
# Warbler web application assembly configuration file
Warbler::Config.new do |config|
  # Temporary directory where the application is staged
  # config.staging_dir = "tmp/war"
 
  # Application directories to be included in the webapp.
  config.dirs = %w(lib public views config)
 
  # Additional files/directories to include, above those in config.dirs
  # config.includes = FileList["db"]
  config.includes = FileList["appengine-web.xml", "app.rb"]
  # Additional files/directories to exclude
  # config.excludes = FileList["lib/tasks/*"]
 
  # Additional Java .jar files to include.  Note that if .jar files are placed
  # in lib (and not otherwise excluded) then they need not be mentioned here.
  # JRuby and JRuby-Rack are pre-loaded in this list.  Be sure to include your
  # own versions if you directly set the value
  # config.java_libs += FileList["lib/java/*.jar"]
 
  # Loose Java classes and miscellaneous files to be placed in WEB-INF/classes.
  # config.java_classes = FileList["target/classes/**.*"]
 
  # One or more pathmaps defining how the java classes should be copied into
  # WEB-INF/classes. The example pathmap below accompanies the java_classes
  # configuration above. See http://rake.rubyforge.org/classes/String.html#M000017
  # for details of how to specify a pathmap.
  # config.pathmaps.java_classes << "%{target/classes/,}p"
 
  # Gems to be included. You need to tell Warbler which gems your application needs
  # so that they can be packaged in the war file.
  config.gems = ['merb-core', 'extlib']
 
  # The most recent versions of gems are used.
  # You can specify versions of gems by using a hash assignment:
  # config.gems["foo"] = "2.0.2"
 
  # You can also use regexps or Gem::Dependency objects for flexibility or
  # fine-grained control.
  # config.gems << /^merb-/
  # config.gems << Gem::Dependency.new("merb-core", "= 0.9.3")
 
  # Include gem dependencies not mentioned specifically
  config.gem_dependencies = true
 
  # Files to be included in the root of the webapp.  Note that files in public
  # will have the leading 'public/' part of the path stripped during staging.
  # config.public_html = FileList["public/**/*", "doc/**/*"]
 
  # Pathmaps for controlling how public HTML files are copied into the .war
  # config.pathmaps.public_html = ["%{public/,}p"]
 
  # Name of the war file (without the .war)
  config.war_name = "{{name}}"
 
  # Name of the MANIFEST.MF template for the war file. Defaults to the
  # MANIFEST.MF normally generated by `jar cf`.
  # config.manifest_file = "config/MANIFEST.MF"
 
  # Value of environment variables
  # config.webxml.foo.env = ENV['FOO_ENV']
 
  # Application booter to use, one of :rack, :rails, or :merb
  config.webxml.booter = :merb
 
  # When using the :rack booter, "Rackup" script to use.
  # The script is evaluated in a Rack::Builder to load the application.
  # Examples:
  # config.webxml.rackup = %{require './lib/demo'; run Rack::Adapter::Camping.new(Demo)}
  # config.webxml.rackup = require 'cgi' && CGI::escapeHTML(File.read("config.ru"))
 
  # Control the pool of runtimes. Leaving unspecified means
  # the pool will grow as needed to service requests. It is recommended
  # that you fix these values when running a production server!
  # config.webxml.jruby.min.runtimes = 2
  # config.webxml.jruby.max.runtimes = 4
  config.webxml.jruby.min.runtimes = 1
  config.webxml.jruby.max.runtimes = 1
  config.webxml.jruby.init.serial = true
 
  config.java_libs = []
end
