# This application files as generated by jruby-enginize.

begin
  require 'appengine-apis/merb-logger'
rescue Exception
end

# Class EngineApp implements the only controller of this application.

class EngineApp < Merb::Controller
  layout :engine_app

  # Returns the location of the template depending on controller and action.
  # Modified to match our flat world.
  #
  # Parameters:
  #
  # [action] Name of the action
  # [type] Requested format
  # [controller] Name of the controller

  def _template_location(action, type = nil, controller = controller_name)
    (controller == 'layout' ? "layout.#{action}.#{type}" : "#{action}.#{type}")
  end

  # GET /

  def index
    render
  end
end
