# This application file was generated by jruby-enginize.

require 'rubygems'

require 'haml'
require 'sass'
require 'sinatra'

# Use AppEngine::URLFetch.fetch() for loading remote files.

require 'appengine-apis/urlfetch'

# Set to true if you need sessions.

set :sessions, false

# Configure Sinatra to reload during development.

class Sinatra::Reloader < Rack::Reloader 
   def safe_load(file, mtime, stderr = $stderr) 
     ::Sinatra::Application.reset!
     stderr.puts "#{self.class}: reseting routes" 
     super 
   end 
end 

configure :development do
  use Sinatra::Reloader
end

# Helpers to include...

helpers do
  include Rack::Utils

  alias_method :h, :escape_html
end

# GET /
 
get '/' do
  haml :index
end

# GET /stylesheet.css

get '/stylesheet.css' do
  content_type 'text/css', :charset => 'utf-8'

  sass :stylesheet
end
