# This application files as generated by jruby-enginize.

require 'rubygems'

begin
  require 'haml'
  require 'sass'
  require 'sinatra'
rescue LoadError => exception
  $stderr.puts '!!missing sinatra. Install sinatra gem and try again.'
  exit(1)
end

# GET /
 
get '/' do
  haml :index
end

# GET /stylesheet.css

get '/stylesheet.css' do
  content_type 'text/css', :charset => 'utf-8'

  sass :stylesheet
end
